// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecureSign.Signature.Infrastructure.Persistence;

#nullable disable

namespace SecureSign.Signature.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SignatureDbContext))]
    [Migration("20260912235009_AgregarPosicionYFirmadoEnFlujo")]
    partial class AgregarPosicionYFirmadoEnFlujo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecureSign.Signature.Domain.FlujoFirma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("FirmadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FirmanteUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("NotificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrdenFirma")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RechazadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SolicitudFirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenAccesoUnico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("VisualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudFirmaId");

                    b.HasIndex("TokenAccesoUnico")
                        .IsUnique();

                    b.HasIndex("FirmanteUsuarioId", "Estado");

                    b.ToTable("FlujosFirma", (string)null);
                });

            modelBuilder.Entity("SecureSign.Signature.Domain.SolicitudFirma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteIntegradorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoVerificacionPublico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("FechaLimite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequiereOrdenSecuencial")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoFirma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoVerificacionPublico")
                        .IsUnique();

                    b.HasIndex("TenantId", "Estado");

                    b.ToTable("SolicitudesFirma", (string)null);
                });

            modelBuilder.Entity("SecureSign.Signature.Domain.FlujoFirma", b =>
                {
                    b.HasOne("SecureSign.Signature.Domain.SolicitudFirma", null)
                        .WithMany("Flujos")
                        .HasForeignKey("SolicitudFirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SecureSign.Signature.Domain.PosicionFirma", "Posicion", b1 =>
                        {
                            b1.Property<Guid>("FlujoFirmaId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Alto")
                                .HasColumnType("double precision")
                                .HasColumnName("PosicionAlto");

                            b1.Property<double>("Ancho")
                                .HasColumnType("double precision")
                                .HasColumnName("PosicionAncho");

                            b1.Property<int>("NumeroPagina")
                                .HasColumnType("integer")
                                .HasColumnName("PosicionNumeroPagina");

                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("PosicionX");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("PosicionY");

                            b1.HasKey("FlujoFirmaId");

                            b1.ToTable("FlujosFirma");

                            b1.WithOwner()
                                .HasForeignKey("FlujoFirmaId");
                        });

                    b.Navigation("Posicion");
                });

            modelBuilder.Entity("SecureSign.Signature.Domain.SolicitudFirma", b =>
                {
                    b.Navigation("Flujos");
                });
#pragma warning restore 612, 618
        }
    }
}
