<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Services\SecureSign.Documents\SecureSign.Documents.Infrastructure\SecureSign.Documents.Infrastructure.csproj" />
    <ProjectReference Include="..\Services\SecureSign.Signature\SecureSign.Signature.Infrastructure\SecureSign.Signature.Infrastructure.csproj" />
    <ProjectReference Include="..\Services\SecureSign.Evidence\SecureSign.Evidence.Infrastructure\SecureSign.Evidence.Infrastructure.csproj" />
    <ProjectReference Include="..\Services\SecureSign.Identity\SecureSign.Identity.Infrastructure\SecureSign.Identity.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
