<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>securesign-secretos</AssemblyName>
    <RootNamespace>SecureSign.SecretTool</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\SecureSign.Shared.Auth\SecureSign.Shared.Auth.csproj" />
  </ItemGroup>

</Project>
