// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecureSign.Evidence.Infrastructure.Persistence;

#nullable disable

namespace SecureSign.Evidence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EvidenceDbContext))]
    partial class EvidenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecureSign.Evidence.Domain.EventoEvidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DatosContextuales")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("HashEvento")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("HashEventoAnterior")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoEvidencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("TenantId", "RegistradoEn");

                    b.ToTable("Evidencias", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
