<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SecureSign.Signature.Domain\SecureSign.Signature.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\SecureSign.Application\SecureSign.Application.csproj" />
    <ProjectReference Include="..\..\SecureSign.Identity\SecureSign.Identity.Domain\SecureSign.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\SecureSign.Pades\SecureSign.Pades.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\SecureSign.Tsa\SecureSign.Tsa.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.10.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
